name: Resource changed

on: repository_dispatch

jobs:
  resource-changed:
    runs-on: ubuntu-latest
    name: Resource changed
    steps:
      - name: Resource Changed step
        run: |
          echo "$ALLMYSECRETS"
          echo "$ALLMYVARS"
        shell: bash
        env:
          ALLMYSECRETS: ${{ toJSON(secrets) }}
          ALLMYVARS: ${{ toJSON(vars) }}
